[build-system]
requires = [
    "setuptools>=77",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "proton-autogen"
version = "3.3.8"
description = "Automatic Proton/Wine launcher"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
authors = [
  { name = "N3oRay" }
]
dependencies = [
  "pyyaml",
  "pygobject",
  "rich",
  "requests",
  "psutil",
  "python-xlib"
]

[tool.pytest.ini_options]
markers = [
    "unit: unit tests",
]

[tool.setuptools]
include-package-data = false

[tool.setuptools.package-dir]
proton_autogen = "usr/lib/python3/dist-packages/proton_autogen"

[tool.setuptools.packages.find]
where = ["usr/lib/python3/dist-packages"]
include = ["proton_autogen*"]
namespaces = false

[tool.setuptools.package-data]
proton_autogen = [
"**/*.json",
"**/*.csv",
"**/*.css",
"**/*.jpg",
"**/*.png",
"**/*.svg",
]
