name: Build Debian Package

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove Microsoft repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo rm -f /etc/apt/sources.list.d/azure-cli.list

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y \
            build-essential \
            devscripts \
            debhelper \
            fakeroot \
            python3 \
            python3-gi \
            python3-yaml \
            python3-rich \
            gir1.2-gtk-4.0 \
            libglib2.0-dev \
            gobject-introspection

      - name: Build package
        run: |
          dpkg-buildpackage -b -us -uc

      - name: Move artifacts into workspace
        run: |
          mkdir -p dist
          mv ../proton-autogen_*.deb dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: proton-autogen
          path: dist/*.deb
